### PR TITLE
The ASE Workshop presentation

### PR DESCRIPTION
**Pull request by blindij**
This presentation was held at the ASE Workshop in Chalmers Nov 19 - 22,
https://ase-workshop.materialsmodeling.org

### CODE REVIEW

**Comment by wikfeldt** [comment]
great presentation! is the idea to replace the existing modular code devel slide stack?

**Comment by blindij** [comment]
The idea was to have a copy in the CodeRefinery repo. I don't  think the talk can  replace the current modular development talk. I am thinking about merging the two talks, but that will need some more work (and discussion as well).

**Comment by bast** [comment]
I think these should perhaps be two repositories which will have some overlap but that's OK but the lesson will probably evolve into more exercise/discussion.

**Comment by bast** [comment]
This is very good material but I don't think this repo is the right place for them (the slides give an overview of topics beyond this one). I will apply changes to the lesson in the coming days which will make this PR conflict. I would like to close this PR but before doing that I want to make sure that the changes are saved somewhere else.

**Comment by rkdarst** [comment]
This is an old PR, and we should find a resolution for it. @blindij, would you like to make a new repository under coderefinery and put it there?

**Comment by rkdarst** [comment]
I think we should decide to either use, or close this PR.  It seems like it would rather fit in another repository.  Should I move it to another CR repository?

**Comment by bast** [comment]
From my perspective this clearly fits better to be a separate repository. I am happy to help moving this. @blindij what is your opinion?

**Comment by bast** [comment]
I am moving this to another repo. I see that this will not break links for the original slides: https://ase-workshop.materialsmodeling.org/abstracts/bjorn-lindi/

**Comment by bast** [comment]
Moved to https://github.com/coderefinery/ase-workshop-2019. Closing.

**Pull request closed without merging**
